/**
 * Live Tor exit node list (https://check.torproject.org/torbulkexitlist,
 * one IPv4 per line, regenerated by the Tor Project roughly every 30-60 min).
 *
 * The list is refreshed in the background and cached on disk. When a download
 * fails, the previous list stays in use; `status()` reports how old it is.
 * Limitation: the bulk list holds the addresses exits *connect from*; an exit
 * with a different outbound address is missed until the list catches up.
 */
import { isIPv4 } from 'net';
import { Logger } from '../../utils/logger.js';
import { FEED_URLS, Fetcher, fetchText, parsePlainList, readCache, writeCache } from '../threat-intel/feeds.js';

export interface TorExitNodeCheckerOptions {
  url?: string;
  /** Background refresh interval; default 1 hour */
  refreshIntervalMs?: number;
  /** Directory for the on-disk copy (survives restarts, works offline) */
  cacheDir?: string;
  fetcher?: Fetcher;
  timeoutMs?: number;
}

export interface TorListStatus {
  count: number;
  /** When the list in use was downloaded (0 = never) */
  updatedAt: number;
  source: 'none' | 'network' | 'cache' | 'manual';
  lastError?: string;
}

export class TorExitNodeChecker {
  private nodes: Set<string> = new Set();
  private state: TorListStatus = { count: 0, updatedAt: 0, source: 'none' };
  private timer: ReturnType<typeof setInterval> | null = null;
  private inflight: Promise<TorListStatus> | null = null;
  private logger = new Logger('TorExitNodeChecker');

  constructor(private options: TorExitNodeCheckerOptions = {}) {
    const cached = readCache(options.cacheDir, 'tor');
    if (cached) this.load(cached.text, cached.fetchedAt, 'cache');
  }

  public isExitNode(rawIp: string): boolean {
    const ip = rawIp.startsWith('::ffff:') ? rawIp.slice(7) : rawIp;
    return isIPv4(ip) && this.nodes.has(ip);
  }

  /** Replace the list from text in torbulkexitlist format (tests, air-gapped setups). */
  public load(text: string, updatedAt = Date.now(), source: TorListStatus['source'] = 'manual'): number {
    const { entries } = parsePlainList(text);
    // Only single addresses are meaningful here; ranges would over-block
    this.nodes = new Set(entries.filter(e => !e.includes('/')));
    this.state = { count: this.nodes.size, updatedAt, source };
    return this.nodes.size;
  }

  /** Download the current list. Concurrent calls share one request. */
  public refresh(): Promise<TorListStatus> {
    this.inflight ??= (async () => {
      try {
        const text = await fetchText(this.options.url ?? FEED_URLS.tor, {
          fetcher: this.options.fetcher, timeoutMs: this.options.timeoutMs,
        });
        // A truncated or empty download must not wipe a good list
        if (parsePlainList(text).entries.length === 0) throw new Error('downloaded Tor list is empty');
        const count = this.load(text, Date.now(), 'network');
        writeCache(this.options.cacheDir, 'tor', text);
        this.logger.info('Tor exit list updated', { count });
      } catch (error) {
        this.state = { ...this.state, count: this.nodes.size, lastError: (error as Error).message };
        this.logger.warn('Tor exit list refresh failed; keeping the previous list', { error: (error as Error).message });
      } finally {
        this.inflight = null;
      }
      return this.status();
    })();
    return this.inflight;
  }

  /** Refresh now and then periodically. Returns the first refresh. */
  public start(): Promise<TorListStatus> {
    if (!this.timer) {
      this.timer = setInterval(() => { void this.refresh(); }, this.options.refreshIntervalMs ?? 60 * 60_000);
      this.timer.unref?.();
    }
    return this.refresh();
  }

  public stop(): void {
    if (this.timer) clearInterval(this.timer);
    this.timer = null;
  }

  public status(): TorListStatus {
    return { ...this.state };
  }
}
