"""Regenerate data_dictionary.md (run from anywhere: python docs/thesis/irb/generate_data_dictionary.py).

Built from the code that collects the data, so the list cannot drift from it:
contracts/features.json (aggregate features), study/aegis_study/raw_events.py
(raw event types), study/aegis_study/i18n.py (survey questions) and
study/aegis_study/db.py (stored fields). A test fails when the committed
file differs from what this script writes.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "study"))

from aegis_study.i18n import SURVEY, TEXT, option_label  # noqa: E402
from aegis_study.raw_events import KEY_CATEGORIES, RAW_EVENTS  # noqa: E402


def build() -> str:
    contract = json.loads((ROOT / "contracts" / "features.json").read_text(encoding="utf-8"))
    lines = [
        "# Data Dictionary — AEGIS Bot Detection Study",
        "",
        "_Generated by `generate_data_dictionary.py` from the code that collects the data "
        "(`contracts/features.json`, `study/aegis_study/`), so this list cannot drift from the software._",
        "",
        "Everything below is recorded only **after** the participant has given consent on the study website. "
        "Sections 1, 2, 4 and 5 apply to every participant; section 3 only to participants who also tick the "
        "**optional** raw-timing box. Bot sessions run by the researcher are recorded the same way.",
        "",
        "## 1. Behavioural summary features (every participant)",
        "",
        "Aggregate numbers computed in the participant's browser (mouse, keyboard, scroll, touch, fingerprint) "
        "or on the study server (session, network), reported every 15 seconds while a page is open and when "
        "it is left.",
        "",
    ]
    count = 0
    for category, spec in contract["categories"].items():
        where = "computed in the browser" if spec["source"] == "sdk" else "computed on the study server"
        lines += [f"### {category.capitalize()} ({where})", "", "| # | Feature | Unit | Meaning |",
                  "|---|---------|------|---------|"]
        for name, unit, meaning in spec["features"]:
            count += 1
            lines.append(f"| {count} | `{name}` | {unit} | {meaning} |")
        lines.append("")
    lines += [
        f"Total: {count} features per report. Stored with each report:",
        "",
        "| Field | Content | Identifying? |",
        "|-------|---------|--------------|",
        "| `page`, `task` | Page of the study shop (e.g. `/shop/login`) and the task being done | No |",
        "| `stream` | Random id of the page view | No |",
        "| `received` | Server time of the report | No |",
        "| `headless_checks`, `anti_detect` | Names of automation checks that fired | No |",
        "| `rule_score`, `ml_probability`, `score`, `verdict` | Detection outputs (the site never blocks anyone) | No |",
        "",
        "## 2. Session, survey and task progress (every participant)",
        "",
        "| Field | Content | Identifying? |",
        "|-------|---------|--------------|",
        "| `code` | Study code given by the researcher (e.g. `H-7KQ2M9XA`). In the exported dataset it is replaced "
        "by a salted hash (`participant`) | Pseudonymous: linked to a name only through the researcher's "
        "separate key list |",
        "| `session_no`, `started`, `finished`, `status` | Which session of this code, start/end time, completed or not | No |",
        "| `lang`, `consent_version`, `consent_at`, `raw_consent` | Language, version and time of the consent, "
        "whether the optional raw-timing box was ticked | No |",
        "| `ua_family`, `ua_major`, `os_family`, `mobile` | Browser family and major version (e.g. Chrome 141), "
        "operating system family (e.g. Android), phone or not. The full browser identification string is not stored | No |",
        "| task events | For each task: start, completion or skip time; unsuccessful attempts. Outcome details "
        "only as yes/no values (e.g. \"search matched the task\", one per checkout field), the length and star "
        "rating of the review | No |",
        "| task targets | The dummy username/password, product, category and delivery details the site generated "
        "for this session | No (invented values) |",
        "",
        "Survey (every question optional; only the chosen option is stored):",
        "",
        "| Question | Options |",
        "|----------|---------|",
    ]
    for phase in ("pre", "post"):
        for key, text_key, options in SURVEY[phase]:
            labels = ", ".join(option_label("en", o) for o in options) + ", Prefer not to say"
            when = "before the tasks" if phase == "pre" else "after the tasks"
            lines.append(f"| {TEXT['en'][text_key]} ({when}) | {labels} |")
    lines += [
        "",
        "## 3. Raw timing events (only with the optional consent)",
        "",
        "The times and screen positions of individual input events in the study website, so that the summary "
        "features can be recomputed and checked later. Each event is a type, a time in milliseconds since the "
        "page was opened, and the fields below. Positions are in pixels of the browser window.",
        "",
        "| Type | Fields | Meaning |",
        "|------|--------|---------|",
    ]
    for code, (fields, meaning) in RAW_EVENTS.items():
        lines.append(f"| `{code}` | {fields} | {meaning} |")
    lines += [
        "",
        "Instead of the key, only one of these categories is recorded: "
        + "; ".join(f"`{k}` {v}" for k, v in KEY_CATEGORIES.items()) + ". "
        "The \"press number\" only pairs a key's press with its release. Form fields are identified by their "
        "name in the study shop (e.g. `username`, `note`), never by their content. Element roles are labels of "
        "the study shop's own buttons and links (e.g. `button:add-to-cart`).",
        "",
        "## 4. Request metadata (every request to the study website)",
        "",
        "| Field | Content | Identifying? |",
        "|-------|---------|--------------|",
        "| `route`, `method`, `status`, `duration_ms`, `at` | Page pattern without ids or search text "
        "(e.g. `/shop/product/{id}`), method, response status, time | No |",
        "| `header_names`, `header_flags` | Names and order of the browser's request headers, and whether "
        "certain headers are present (no header values) | No |",
        "| `ua_family`, `ua_major`, `os_family` | As in section 2 | No |",
        "| `aegis_action`, `aegis_score`, `aegis_reason` | Detection output for the request | No |",
        "",
        "Requests made before consent, or by visitors without a study code, are stored without any link to "
        "a participant (\"unlabelled\") and are analysed separately.",
        "",
        "## 5. Processed but NOT stored",
        "",
        "| Data | Why it is processed | Retention |",
        "|------|--------------------|-----------|",
        "| IP address | Network features (datacenter/Tor flags), limiting wrong study-code attempts | Memory only. "
        "No access logs are written |",
        "| Full browser identification string (user agent) | Header checks; a hash binds the token to the browser | Memory only |",
        "| Header values, search text, form contents (username, password, address, notes, reviews) | Showing "
        "the shop and checking whether a task was completed | Memory only, during the request |",
        "| Device fingerprint hash | Session consistency check | Memory only |",
        "| Cookies `aegis_sid` and `study_sid` | Group the requests of one visit | Expire after the visit "
        "(30 min inactivity / 6 h) |",
        "",
        "## 6. Never collected",
        "",
        "- Which keys were pressed or any typed text (the login and delivery details are invented values given "
        "by the site)",
        "- Screenshots, screen recordings, webcam, microphone, location, device motion",
        "- Clipboard content (only that a paste happened)",
        "- Browsing history or activity on other sites or other browser tabs",
        "- Names, e-mail addresses or phone numbers of participants (only on the paper consent form / "
        "the researcher's separate key list)",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    out = Path(__file__).parent / "data_dictionary.md"
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
