{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aegis.fullname" . }}
  labels:
    {{- include "aegis.labels" (dict "root" . "component" "metrics") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchExpressions:
      - { key: app.kubernetes.io/instance, operator: In, values: [{{ .Release.Name | quote }}] }
      - { key: app.kubernetes.io/component, operator: In, values: [api-python, api-node] }
  endpoints:
    - port: http
      path: /aegis/metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
