#!/bin/sh
# Render the chart's defaults into plain manifests (deploy/kubernetes/aegis.yaml) for
# clusters without Helm. The secret is not rendered: create it first, see deploy/README.md.
set -eu
cd "$(dirname "$0")"
mkdir -p kubernetes
{
  echo "# Generated by deploy/render-manifests.sh from deploy/helm/aegis (default values). Do not edit."
  echo "# kubectl create secret generic aegis-secret --from-literal=AEGIS_SECRET_KEY=\$(openssl rand -hex 32)"
  echo "# kubectl apply -f deploy/kubernetes/aegis.yaml"
  helm template aegis helm/aegis --set secret.existingSecret=aegis-secret --skip-tests
} > kubernetes/aegis.yaml
